<a href="https://colab.research.google.com/github/Shigellicious/Shigellicious/blob/main/harry_potter_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook I will program to look for every word in the books first four books from de Harry Potter series written by J. K. Rowling.
I found the harry potter books file in this URL: https://github.com/amephraim/nlp/tree/master/texts
The .txt files are located at my drive and I will work with python from there.
I am thankfull to Michigan University, because i started studying programming and python from their Coursera corses.  

In [1]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)




Mounted at /content/drive


hp1, hp2, hp3 and hp4 are variables which I used to place all Strings from each txt file using the method read.

In [19]:
hp1 = open ("/content/drive/My Drive/harry_potter_txt/harry_potter_1.txt","r") 
hp2 = open ("/content/drive/My Drive/harry_potter_txt/harry_potter_2.txt","r") 
hp3 = open ("/content/drive/My Drive/harry_potter_txt/harry_potter_3.txt","r") 
hp4 = open ("/content/drive/My Drive/harry_potter_txt/harry_potter_4.txt","r")  

In this next block of code I created a list of lines of th whole text and put it on the variable list_hp1. I put a print method to show how many lines we have in the book. (The answer is 10702 lines).

In [3]:
list_hp1 = hp1.readlines()
print (len(list_hp1))


10702


In this next part I am priting the lines from 101 to 105, We have to remember that python starts with index 0, so to know what line we are talking about we need to add 1 to the list index used.

In [4]:

print (list_hp1[100])
print (list_hp1[101])
print (list_hp1[102])
print (list_hp1[103])
print (list_hp1[104])


secretary not to disturb him, seized his telephone, and had almost

finished dialing his home number when he changed his mind. He put the

receiver back down and stroked his mustache, thinking... no, he was

being stupid. Potter wasn't such an unusual name. He was sure there were

lots of people called Potter who had a son called Harry. Come to think



Now I am creating an algoritm that cleans the words in each line from the pontuation on pontuation list

In [5]:
print (list_hp1[102].split()) #this is the list with all words in the line with the pontuation.
pontuation_list = ["!", ",", ".", "(", ")", "?", "...", """"""", """""""]
clean_list = []
clean_word = ""
for word in list_hp1[102].split():
  for char in word:
    if char not in pontuation_list:
      clean_word = clean_word + char
  
  clean_list.append(clean_word)
  clean_word = "" #this reset the clean_word String, if we dont do that it will join all letters from each word in the line together.
print(clean_list)#this is the list with all the words in the line but without the pontuation from the pontuation list.
  


['receiver', 'back', 'down', 'and', 'stroked', 'his', 'mustache,', 'thinking...', 'no,', 'he', 'was']
['receiver', 'back', 'down', 'and', 'stroked', 'his', 'mustache', 'thinking', 'no', 'he', 'was']


The next Step is to create a function called pontuatation_remover that recives a list as a parameter and returns a list with all words from  the line used as parameter to the function without the pontuation from the pontuation_list.

In [6]:
def pontuation_remover(some_list):
  pontuation_list = ["!", ",", ".", "(", ")", "?", "...","\"", "\"", "-", " ", "\n", ":", ";" ] #backslash is scape sequence that allows me to use double quote as string, I could use single quote to use double quote as a string
  clean_list = []
  clean_word = ""
  for word in some_list.split():
    for char in word:
      if char not in pontuation_list:
        clean_word = clean_word + char
  
    clean_list.append(clean_word)
    clean_word = "" 
  return clean_list

As we can see we got the same result them before with the function pontuation_remover.

In [7]:
a = pontuation_remover(list_hp1[7572])
print (a)

['hardly', 'heard', 'a', 'word', 'of', "Wood's", 'pep', 'talk', 'as', 'he', 'pulled', 'on', 'his', 'Quidditch']


Now is time to use that function for all the lines in the first book of the Harry Potter series, remember that I said that it has 10702 lines (len(list_hp1)). I used 2 for loops here, one to go throgh the list of lists that is list_hp1, then I used a second for lop to itarate trough all the words in each list inside list_hp1 to append those words inside the hp1_words_list. I had to use a other list called b just to hold the information that my fuction return to me and i itarate trough that list to get all words inside it, once that was finished I had to change b value to a empty list to start the whole processes again.


In [8]:
hp1_words_list = []
for line in list_hp1:
  b = pontuation_remover(line)
  for word in b:
    hp1_words_list.append(word)
  b =[]


This is just a print to show the first fifty itens inside hp1_words_list to show that it work. We can see that its length is = 78451, which means that in the first Harry Potter book we have 78451 words, but I have to mention that I** didn't take in consideration auxiliary verbs** such as had,would, should and others in words like "you'd" and others contractioned words.

In [9]:
print (hp1_words_list[:50])
print(len(hp1_words_list))

['Harry', 'Potter', 'and', 'the', "Sorcerer's", 'Stone', 'CHAPTER', 'ONE', 'THE', 'BOY', 'WHO', 'LIVED', 'Mr', 'and', 'Mrs', 'Dursley', 'of', 'number', 'four', 'Privet', 'Drive', 'were', 'proud', 'to', 'say', 'that', 'they', 'were', 'perfectly', 'normal', 'thank', 'you', 'very', 'much', 'They', 'were', 'the', 'last', 'people', "you'd", 'expect', 'to', 'be', 'involved', 'in', 'anything', 'strange', 'or', 'mysterious', 'because']
78451


We can se by the length of the list contractioned_words that we in the 78451 total words inside the book, we have 2690 contractioned words. We can see that some itens of the list has only the "'ve" or "'t", to be honest I don't what went wrong there, but definitely it is a contracioned word. I forgot to say that contractions is a list with the most commom contractions that I found in english, if there is an contraction inside the book that i didn' put inside that list it will not appear inside the contractioned_words list. Another thing that I have to say about my code is the word[-3:] and word[-2:], this means that for every word inside the hp1_words_list I will compare the last three or two letters to compare with my contractions list, if then are equal to one of the itens of the contractions list, that word is appened to my contractioned_words list. I needed only the last 3 or 2 letters to see if it is a contractioned word, also it's important to see that inside those 3 or 2 charecters we have the single quote ' .

In [10]:
contractions = ["'d","'ve","'s","'ll","'re","'m", "'t"]
contractioned_words = []
for word in hp1_words_list:
  for contraction in contractions:
    if word[-3:] == contraction:
      contractioned_words.append(word)
    elif word[-2:] == contraction:
      contractioned_words.append(word)


print (len(contractioned_words))
print (contractioned_words[:50])

2690
["Sorcerer's", "you'd", "didn't", "didn't", "Dursley's", "hadn't", "didn't", "didn't", "four's", "didn't", "wasn't", "couldn't", "couldn't", "couldn't", "weren't", "hadn't", "didn't", "he'd", "He'd", "baker's", "didn't", "couldn't", "that's", "that's", "wasn't", "wasn't", "He'd", "didn't", "he'd", "didn't", "Don't", "didn't", "didn't", "he'd", "didn't", "Door's", "Won't", "nation's", "don't", "it's", "they've", "it's", "He'd", "haven't", "didn't", "he'd", "didn't", "he'd", "Dudley's", "wouldn't"]


Now we are goin create a dictionary for each word inside the list hp1_words_list, at the begining the dictionary words_frequency is empty, but we are going to intinarate trhough our list and use condionals to help us see which word has been added to list, if the word has been considerated we are going to add 1 to the value of that word, that is they key of our dictionary. If there isnt a key with the value of the word it will be add to the dictionary with the value 1.

In [11]:
words_frequency_hp1 = {}
for word in hp1_words_list:
  w = word.lower()
  if w not in words_frequency_hp1:
    words_frequency_hp1[w] = 1
  else:
    words_frequency_hp1[w] += 1





Here I am just printing some of the names to see how many times each name is mentioned i the book, I forgot to say that I used the method .lower() to make all word lower case, names included. Because if I didn't we were going to have some duplicated words key, some um upper case and some in lower case, for exemple: "harry" and "Harry", "hermione" and "Hermione" and so on.

In [12]:
print (words_frequency_hp1["harry"])
print (words_frequency_hp1["hermione"])
print (words_frequency_hp1["voldemort"])
print (words_frequency_hp1["ron"])
print (words_frequency_hp1["dumbledore"])

1214
257
31
410
142


Here is just another exemple of how the .lower method works with strings.

In [13]:
caps = "CAPSLOCK ON"
print (caps.lower())

capslock on


Here we can see all the words that have appeared 10 times in the book.

In [14]:
keys = words_frequency_hp1.keys()
for key in keys:
  if words_frequency_hp1[key] == 10:
    print ("The word '{}' appeared {} time(s) in the Harry Potter and the Philosopher's stone".format(key, words_frequency_hp1[key]))

The word 'normal' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'thin' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'fear' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'keeping' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'woke' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'chair' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'throwing' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'realize' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'jerked' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'young' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'bag' appeared 10 time(s) in the Harry Potter and the Philosopher's stone
The word 'learned' appeared 10 time(s) in the Harry Potter an

Here we are going to see a list with all the words that has 1 occurrency on the book and the occoruncy of the word or words that is(are) the most used in the book.

In [15]:
best_key = 0
worst_key_list = []
for key in keys:
  if words_frequency_hp1[key] > best_key:
    best_key = words_frequency_hp1[key]
  if words_frequency_hp1[key] == 1:
    worst_key_list.append(key)
print (best_key)
print(worst_key_list)
print(len(worst_key_list))

3628
['beefy', 'amount', 'fences', 'discover', 'goodfornothing', 'husband', 'undursleyish', 'tie', 'gossiped', 'wrestled', 'briefcase', 'pecked', 'cereal', "four's", 'maps', 'signs', 'getups', 'drummed', 'wheel', 'enraged', 'stunt', 'ninth', 'swoop', 'gazed', 'owlfree', 'stretch', 'bakery', "baker's", 'tin', 'doughnut', 'whisperers', 'secretary', 'dialing', 'receiver', 'harvey', 'harold', 'squeaky', 'rejoice', 'approve', 'driveway', 'shoo', 'behavior', "door's", 'daughter', 'act', 'birdwatchers', 'reported', "nation's", 'hunt', 'sightings', 'sunrise', 'experts', 'pattern', 'newscaster', 'mcguffin', 'showers', 'ted', 'weatherman', 'viewers', 'dundee', 'phoning', 'downpour', 'bonfire', 'folks', 'funnylooking', 'sipped', 'pursed', 'howard', 'related', 'affect', 'drifting', 'sleepiness', "cat's", 'judging', 'tuck', 'belt', 'highheeled', 'buckled', 'unwelcome', 'cigarette', 'pinpricks', 'beadyeyed', 'pavement', 'fancy', 'severelooking', 'distinctly', 'livingroom', 'flocks', 'swapping', 'tha

We can se here that the most used word in th book is the word 'the'.

In [16]:
best_key_list =[]
for key in keys:
  if words_frequency_hp1[key] == 3628:
    best_key_list.append(key)
print (best_key_list)

['the']


I have to be honest, I don't have a clue why there is in our list the words "interestinglooking" and "whomustnotbenamed", I really don't. But if we take those words off in the equation, we can see that the biggest lengeth words are those with 9 characteres, and I used another for loop to see which words are those.

In [17]:
biggest_len_word = 0
biggest_words_list = []

for key in keys:
  if (len(key) > biggest_len_word) and key != "interestinglooking" or key != "whomustnotbenamed":
    biggest_len_word = len(key)

for key in keys:
  if len(key) == biggest_len_word:
    biggest_words_list.append(key)

print (biggest_len_word)
print(biggest_words_list)



9
['perfectly', 'grunnings', 'neighbors', "dursley's", 'pretended', 'shuddered', 'happening', 'screaming', 'briefcase', 'something', 'strangely', 'excitedly', 'obviously', 'nighttime', 'different', 'important', 'telephone', 'lunchtime', 'forgotten', 'clutching', 'secretary', 'afternoon', 'passersby', 'imagining', 'unusually', 'sightings', 'direction', 'yorkshire', 'yesterday', 'nervously', 'sparkling', 'unwelcome', 'rummaging', 'cigarette', 'flickered', 'pinpricks', 'beadyeyed', 'professor', "dursleys'", 'celebrate', 'irritably', 'downright', 'certainly', 'voldemort', 'confusing', 'surprised', 'seriously', 'swallowed', 'headlight', 'carefully', 'destroyed', 'curiously', 'lightning', 'whispered', 'shoulders', 'furiously', 'twinkling', 'streaming', 'vanishing', 'screeched', 'questions', 'newspaper', 'difficult', 'meanwhile', 'thirtysix', 'adventure', 'hamburger', 'suggested', 'hopefully', 'listening', 'duddydums', 'christmas', 'sleepless', 'revolting', 'buildings', 'somewhere', 'sniggere

In [18]:
class harryPotter:
    title = "The boy who lived"
    


hp = harryPotter()
print (hp.title)

The boy who lived


SyntaxError: ignored